export const LOGIN = "LOGIN",
  LOGOUT = "LOGOUT",
  GET_TOKEN = "GET_TOKEN",
  LOADING = "LOADING",
  GET_SHOP_INFO = "GET_SHOP_INFO",
  GET_MEMBER_INFO = "GET_MEMBER_INFO",
  GET_STORE_INFO = "GET_STORE_INFO",
  GET_SUPPLIER_INFO = "GET_SUPPLIER_INFO",
  GET_PROFIT_INFO = "GET_PROFIT_INFO",
  AUTH_USER = "AUTH_USER",
  // 分页信息
  MEMBER_META_INFO = "MEMBER_META_INFO",
  SHOP_META_INFO = "SHOP_META_INFO",
  WITHDRAW_META_INFO = "WITHDRAW_META_INFO",
  AREAS_META_INFO = "AREAS_META_INFO",
  PROFIT_SHARE_META_INFO = "PROFIT_SHARE_META_INFO",
  ROLE_TYPE = "ROLE_TYPE",
  // this is reconfiguration ..
  TOAST = 'TOAST'
